### ISSUE TITLE
Installing requirements

### ISSUE THREAD

**Issue by iloveboobs1** [k4m4/kickthemout#110]
`$ pip install -r requirements.txt`
```
Collecting scapy (from -r requirements.txt (line 1))
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 325kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9jgfyswh/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9jgfyswh/scapy/
```

**Comment by R3DDY97** [comment]
@iloveboobs1 
try installing in python 2.7.11
not in python 3.x
Check ur python version

**Comment by k4m4** [comment]
Hi there. This is an issue with `scapy` and not `KickThemOut`. A google search should get the job done. Thanks.
