### ISSUE TITLE
Bash on Ubuntu on Windows not working for this

### ISSUE THREAD

**Issue by notcrunchytaco** [k4m4/kickthemout#118]
`Taco@DESKTOP-2JFG3CL:/kickthemout$ sudo python kickthemout.py
sudo: unable to resolve host DESKTOP-2JFG3CL
Traceback (most recent call last):
  File "kickthemout.py", line 478, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 357, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence`

Thats the error I'm getting I do use WiFi. I have a working wlan card.

**Comment by k4m4** [comment]
Hi there @notcrunchytaco. This issue should now be solved. Are you still experiencing this problem?

**Comment by k4m4** [comment]
Closing due to inactivity. If you are still experiencing this problem, please re-open this issue. Thanks.
