### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by nBlueDev** [k4m4/kickthemout#121]
What is the problem here? Anybody help?

> **MacBook-Pro:kickthemout bluedev$** sudo python kickthemout.py
> 
> ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
> 
> If you still cannot resolve this error, please submit an issue here:
> 	https://github.com/k4m4/kickthemout/issues
------------------------------------------------------------------------------------------------------
> **MacBook-Pro:kickthemout bluedev$** sudo -H pip install -r requirements.txt
> Requirement already satisfied: scapy in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: python-nmap in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
---------------------------------------------
When I run scapy command I got this:

>MacBook-Pro:~ bluedev$ scapy
>INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
>ERROR: Unable to import dnet module: No module named dumbnet
>WARNING: No route found for IPv6 destination :: (no default route?)
>INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
>INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
>INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
>Welcome to Scapy (2.3.3)
.>>>

**Comment by unknownkillerdude** [comment]
i had the same problemo no idea how to fix it

**Comment by unknownkillerdude** [comment]
not had but have

**Comment by R3DDY97** [comment]
@BlueDevelop 

try  running as root user 
`sudo scapy`

**Comment by k4m4** [comment]
Please let us know if @R3DDY97 's response solved your problem. If not, please re-open this issue. Thanks.

**Comment by BlueDevelop** [comment]
`MacBook-Pro:~ bluedev$ sudo -H pip install scapy`
> Requirement already satisfied: scapy in /Library/Python/2.7/site-packages
-----------------------------------
`MacBook-Pro:~ bluedev$ sudo scapy`
> INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
> ERROR: Unable to import dnet module: No module named dumbnet
> WARNING: No route found for IPv6 destination :: (no default route?)
> INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
> INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
> INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
> Welcome to Scapy (2.3.3)
----------------------------------

`MacBook-Pro:~ bluedev$ brew install nmap`
> Warning: nmap 7.50 is already installed

`MacBook-Pro:~ bluedev$ brew install libdnet`
> Warning: libdnet 1.12 is already installed
--------------
BUT scapy over brew,
`MacBook-Pro:~ bluedev$ brew install scapy`
> Error: No available formula with the name "scapy" 
> ==> Searching for a previously deleted formula...
> Error: No previously deleted formula found.
> ==> Searching for similarly named formulae...
> Error: No similarly named formulae found.
> ==> Searching taps...
> Error: No formulae found in taps.

**Comment by k4m4** [comment]
What does `$ sudo kickthemout.py` result to then? @nBlueDev

**Comment by nBlueDev** [comment]
`MacBook-Pro: bluedev$ cd kickthemout`
`MacBook-Pro:kickthemout bluedev$ sudo python kickthemout.py`
> 
> ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
> 
> If you still cannot resolve this error, please submit an issue here:
> 	https://github.com/k4m4/kickthemout/issues

**Comment by k4m4** [comment]
The following should work:
- `$ brew update`
- `$ brew install --with-python libdnet`
- `$ brew install https://raw.githubusercontent.com/secdev/scapy/master/.travis/pylibpcap.rb`

**Comment by nBlueDev** [comment]
No magic with that :(

>`MacBook-Pro:~ bluedev$ brew update`
>Already up-to-date.

> `MacBook-Pro:~ bluedev$ brew install --with-python libdnet`
> Warning: libdnet 1.12 is already installed

> `MacBook-Pro:~ bluedev$ brew install` https://raw.githubusercontent.com/secdev/scapy/master/.travis/pylibpcap.rb
> ######################################################################## 100.0%
> Warning: pylibpcap 0.6.4 is already installed

> `MacBook-Pro:~ bluedev$ scapy`
> INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
> ERROR: Unable to import dnet module: No module named dumbnet
> WARNING: No route found for IPv6 destination :: (no default route?)
> INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
> INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
> INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
> Welcome to Scapy (2.3.3)

> `MacBook-Pro:kickthemout bluedev$ sudo python kickthemout.py`
> ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
> 
> If you still cannot resolve this error, please submit an issue here:
> 	https://github.com/k4m4/kickthemout/issues

Some more suggestions? :/

**Comment by bntzio** [comment]
I'm having the same issues

**Comment by bntzio** [comment]
Just that I get:

`Scanning your network, hang on...
ERROR: Network scanning failed. Please check your requirements configuration.`

**Comment by k4m4** [comment]
Hi again; apologies for the delay. Try running: `$ sudo python2 kickthemout.py`. Thanks.

**Comment by nBlueDev** [comment]
> **k4m4 commented 2 days ago**
> Hi again; apologies for the delay. Try running: $ sudo python2 kickthemout.py. Thanks.

The same error... How can I help you to debug this? I can send you some logs if you want, so this problem can be fixed much faster...

**Comment by k4m4** [comment]
There's not much you can do to help me debug besides letting me know how you tried to install the requirements. This is most probably an issue with scapy, so I would suggest uninstalling it (`brew uninstall scapy` & `pip uninstall scapy`) and trying to install it the manual way, as observed [here](https://github.com/k4m4/kickthemout/issues/126#issuecomment-320682721). Let me know how that goes. Thanks.

**Comment by falbinosantos** [comment]
I'm having the same issues and i already installed scapy the manual way.

**Comment by R3DDY97** [comment]
Try this 
open kickthemout.py file

replace the code lines from lines 30-36 with below  2 lines
and run again 
Then the error output  tells us exactly where and what  exactly went wrong 

`from scapy.all import *
import scan, spoof`

**Comment by R3DDY97** [comment]
Try this
open kickthemout.py file

replace the code lines from lines 30-36 with below 2 lines
and run again
Then the error output tells us exactly where and what exactly went wrong

`from scapy.all import * 

import scan, spoof`

**Comment by R3DDY97** [comment]
Try this
open kickthemout.py file

replace the code lines from lines 30-36 with below 2 lines
and run again
Then the error output tells us exactly where and what exactly went wrong

`from scapy.all import *`
` import scan, spoof`

**Comment by R3DDY97** [comment]
Try this
open kickthemout.py file


replace the code lines from lines 30-36 
`try:
    from scapy.all import *
    import scan, spoof
except:
    print("\n{0}ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.").format(RED)
    print("\n{0}If you still cannot resolve this error, please submit an issue here:\n\t{1}https://github.com/k4m4/kickthemout/issues\n{2}").format(RED, BLUE, END)
    raise SystemExit`

with below 2 lines

`from scapy.all import *`
`import scan, spoof`

and run again
Then the error output tells us exactly where and what exactly went wrong
and can be easily fixed ....

**Comment by falbinosantos** [comment]
I received that: 

```
Felipes-MacBook-Pro:kickthemout Felipe$ sudo python kickthemout.py
Password:
Traceback (most recent call last):
  File "kickthemout.py", line 30, in <module>
    from scapy.all import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/__init__.py", line 79, in <module>
    from scapy.arch.pcapdnet import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 471, in <module>
    import dumbnet as dnet
ImportError: No module named dumbnet
```

But I don't know what exactly it means.

**Comment by R3DDY97** [comment]
@falbinosantos
I think  it gonna fix scapy dependencies error 
And kickthemout will work fine ...

**Comment by R3DDY97** [comment]
@falbinosantos
I think it gonna fix scapy dependencies error
And kickthemout will work fine ...


Update the outcome after installing dumbnet..

**Comment by R3DDY97** [comment]
@falbinosantos
I think it gonna fix scapy dependencies error
And kickthemout will work fine ...

Update the outcome after installing dumbnet..
it might help other Mac OSx users  
and README can be updated ...

**Comment by falbinosantos** [comment]
@R3DDY97 The script is launching, at least. But, unfortunately it is doing nothing when I try to kick somebody out my network. =/

**Comment by usama7628674** [comment]
Ran it on Kali linux,worked for 5 -10 mins and after that I can browse as usual

**Comment by R3DDY97** [comment]
@ falbinosantos 

U can find out the issue by running script after removing
`try

except`
error catching through out script
then u might get to know
why its not kicking someone out of network...

**Comment by jano07** [comment]
Hey I can't excute the sudo pip2 install -r requirements.text I'm using termux emulator for my android I've already installed all the package... Anyone? Can't help me?

**Comment by k4m4** [comment]
Hi @jano07. Unfortunately, KickThemOut is not compatible on Android. Thanks!

**Comment by k4m4** [comment]
Closing due to inactivity.
