### ISSUE TITLE
OSX: IMPORT ERROR : Won't start the .py

### ISSUE THREAD

**Issue by RSickenberg** [k4m4/kickthemout#24]
```
Traceback (most recent call last):
  File "kickthemout.py", line 13, in <module>
    import urllib2 as urllib
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

OS : 10.12.3 Beta (16D30a)

**Comment by k4m4** [comment]
Strange. There seems to be an error when attempting to import the `urllib2` framework, which should be inbuilt with your machine's Python. It is most probably an error with your Python configuration. Let me look into it.

**Comment by RSickenberg** [comment]
It's okay, I just needed to restart / uninstall / install all the stuff :)
