### ISSUE TITLE
No module named 'scapy'

### ISSUE THREAD

**Issue by Tonhy** [k4m4/kickthemout#249]
It helps when installing in parrot, when launching the program with the command (sudo python3 kickthemout.py) I get the following error:

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still can not resolve this error, please submit an issue here:
https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by k4m4** [comment]
Hi there @Tonhy. This is after running `pip3 install -r requirements.txt`, correct?

**Comment by Tonhy** [comment]
Thanks for answering, in relation to your question, yes but when entering in the terminal the command sudo -H pip3 install -r requirements.txt throws me the following:
sudo: pip3: command not found.
So I have to enter the command in this way:
sudo -H python -m pip install -r requirements.txt

and so it runs correctly, but when you enter: sudo python3 kickthemout.py I get no module named scapy, likewise I already verified, and if I have Scapy installed, I also uninstall parrot and install Kali linux, but it throws me exactly the same

**Comment by k4m4** [comment]
This is most probably because you are running `sudo -H python ...` instead of `sudo -H python3 -m pip install -r requirements.txt`.

**Comment by MaIsma** [comment]
hi, i get the same error and then i did the commande sudo -H python3 -m pip install -r requirements.txt but then i got the error :

` sudo -H python3 -m pip install -r requirements.txt
Collecting scapy-python3 (from -r requirements.txt (line 1))
  Using cached scapy-python3-0.23.tar.gz
Collecting python-nmap (from -r requirements.txt (line 2))
  Using cached python-nmap-0.6.1.tar.gz
Collecting netifaces (from -r requirements.txt (line 3))
  Using cached netifaces-0.10.6.tar.gz
Installing collected packages: scapy-python3, python-nmap, netifaces
  Running setup.py install for scapy-python3 ... done
  Running setup.py install for python-nmap ... done
  Running setup.py install for netifaces ... done
Successfully installed netifaces-0.10.6 python-nmap-0.6.1 scapy-python3-0.23
macMes-MacBook-Pro:kickthemout macme$ sudo python3  kickthemout.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 129, in checkInternetConnection
    urlopen('https://google.com', timeout=3)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 739, in <module>
    if checkInternetConnection():
  File "kickthemout.py", line 131, in checkInternetConnection
    except urllib.URLError as err:
NameError: name 'urllib' is not defined`

**Comment by k4m4** [comment]
This is an issue with your Python configuration. Try following the suggestions on [here](https://github.com/tensorflow/tensorflow/issues/10779). Let me know if that helps.

**Comment by MaIsma** [comment]
Yes that work need to do this command in the terminal 
`/Applications/Python\ 3.6/Install\ Certificates.command`
thanks

**Comment by FAL5E** [comment]
Hello the first mistake I could solve it, but now I throw this other, the truth is I am 30 years old and I am self-taught and before asking a question that I consider stupid, I investigate and check out thousands of solutions, but if my problem is something half awkward, A thousand apologies, I hope you can help me.

ERROR: 

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Collecting python-nmap (from -r requirements.txt (line 2))
  Could not fetch URL https://pypi.python.org/simple/python-nmap/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement python-nmap (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for python-nmap (from -r requirements.txt (line 2))

**Comment by k4m4** [comment]
@FAL5E did this error occur after running `pip3 install -r requirements.txt`?

**Comment by k4m4** [comment]
@FAL5E any progress with this?

**Comment by Exarcun** [comment]
apt-get install python (and python3)
apt-get install python-pip3

then run the sudo -H python3 -m pip install -r requirements.txt

worked out for me :)

**Comment by Exarcun** [comment]
***python3-pip

**Comment by 45ashok** [comment]
bro i also get the same error .plz give me the command lines to solve the problem i dont know wat to do

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
 No module named 'scapy'

**Comment by k4m4** [comment]
@45ashok Please refer to the installation process in the readme file.

**Comment by k4m4** [comment]
Closing due to inactivity. If anyone is still experiencing this problem, please create a new issue. Thanks!

**Comment by zacharymcarr44** [comment]
Yes I am sorry behind on mail


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by usman1644** [comment]
Hi 
I have problem with scapy 
i have already install scapy but again below error is comming 

Traceback (most recent call last):
  File "h1.py", line 160, in <module>
    import scapy
ImportError: No module named 'scapy'

**Comment by k4m4** [comment]
Hi @usman1644. Please make sure that you are following the installation instructions as stated in the readme file. Thanks.

**Comment by NickWho** [comment]
@usman1644 Hi,
Did you tried to install the Requirements in this Way: "sudo -H pip install -r requirements.txt" ? 
Like removing the 3 from the pip? that's actually the Way i fixed the Issue for me. If it's still not working, then just install/check in Synaptic if you have installed all the needs for kickthemout.py

**Comment by ahmedalisha** [comment]
Hi i have a problem with scapy  and getting this error

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting scapy-python3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d4/f2/14ae91e83cd98856879a7322406bed27053a8da23f4cf8218a2f5feedea9/scapy-python3-0.25.tar.gz
Collecting python-nmap (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/dc/f2/9e1a2953d4d824e183ac033e3d223055e40e695fa6db2cb3e94a864eaa84/python-nmap-0.6.1.tar.gz
Collecting netifaces (from -r requirements.txt (line 3))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 827, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  [Previous line repeated 1 more times]
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/99/9e/ca74e521d0d8dcfa07cbfc83ae36f9c74a57ad5c9269d65d1228c5369aff/netifaces-0.10.7-cp36-cp36m-manylinux1_x86_64.whl (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

**Comment by methoomirza** [comment]
apt-get install python 
apt-get install python3
apt-get install python3-pip

then run the sudo -H python3 -m pip install -r requirements.txt

worked for me :)
