### ISSUE TITLE
Kickthemout failing to run correctly

### ISSUE THREAD

**Issue by tryfontheo** [k4m4/kickthemout#264]
Macbook Pro 2016 High Sierra with newest versions of home-brew, python 2.7 and 3.6, scapy, other requirements, etc.

Getting this error when running with just normal sudo python kickthemout.py :

Tryfons-MBP:kickthemout tryfon$ sudo python kickthemout.py 
Password:

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function

When running sudo python3 kickthemout.py I get this :

Tryfons-MBP:kickthemout tryfon$ sudo python3 kickthemout.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 129, in checkInternetConnection
    urlopen('https://google.com', timeout=3)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 740, in <module>
    if checkInternetConnection():
  File "kickthemout.py", line 131, in checkInternetConnection
    except urllib.URLError as err:
NameError: name 'urllib' is not defined

**Comment by tryfontheo** [comment]
Lots of troubleshooting later I got it to work :)

**Comment by tryfontheo** [comment]
Unfortunately yes. Only works via ethernet

**Comment by k4m4** [comment]
Have you tried installing the latest version of KickThemOut, with python3?

**Comment by tryfontheo** [comment]
It seems as though the most recent update of python fixed the issue

**Comment by k4m4** [comment]
Sounds good.

**Comment by tryfontheo** [comment]
No longer working as of now. I'm certain that I changed nothing and it still hangs on this screen 
<img width="644" alt="screen shot 2018-04-16 at 9 15 30 am" src="https://user-images.githubusercontent.com/23111073/38811107-bbf88b70-4156-11e8-8e48-bf06c1376293.png">
