### ISSUE TITLE
ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)

### ISSUE THREAD

**Issue by ironwolf97** [k4m4/kickthemout#268]
Traceback (most recent call last):
  File "kickthemout.py", line 784, in <module>
    main()
  File "kickthemout.py", line 619, in main
    heading()
  File "kickthemout.py", line 57, in heading
    '\n' + 'Version: {}2.0{} \n'.format(YELLOW, END).center(86))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)

how do i fix this

**Comment by k4m4** [comment]
Hi there. Which version of python3 are you using?

**Comment by DuelUtility** [comment]
Hi! I'm having the same issue error, but at slightly different lines. I'm running Python 3.6.5 from Homebrew.

Traceback (most recent call last):
  File "kickthemout.py", line 788, in <module>
    main()
  File "kickthemout.py", line 623, in main
    heading()
  File "kickthemout.py", line 58, in heading
    '\n' + 'Version: {}2.0{} \n'.format(YELLOW, END).center(86))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)

**Comment by NaimJones16** [comment]
> Closing due to inactivity; assuming that the issue has been resolved. If the problem persists, please feel free to re-open the issue. Thanks!

Hi I had the exact same issue and it has not been resolved after closing the app.

When running the sudo python3  kickthemout.py  it stalls for a long period of time then I run the ctrl +c to escape, type in my router address and it will show the original posts question.

Anything you suggest doing.?

**Comment by borekon** [comment]
It's a enconding displaying... the header colors......
Just add a # in the [line 626](https://github.com/k4m4/kickthemout/blob/861aea2102369b2e8c5d86db39d6a5a4d130d02f/kickthemout.py#L626) to make the program not calling the banner and info option
