### ISSUE TITLE
Error while running the python script 

### ISSUE THREAD

**Issue by amanbansal2709** [k4m4/kickthemout#282]
Hey, I have installed all dependencies required to run this but still throwing me the below error:
```
root@kali:~/Downloads/kickthemout-master# python3 kickthemout.py 
Traceback (most recent call last):
  File "kickthemout.py", line 750, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 153, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)
```

Any suggestions?

**Comment by k4m4** [comment]
Hi there. What version of python3 are you running and what version of pip3 did you use to install dependencies?

**Comment by k4m4** [comment]
Closing this due to inactivity of creator. Please refer to #284 for developments on this issue. Thanks!
