### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by melkopisi** [k4m4/kickthemout#284]
I've got a new router and when i try to use the script i face this error : 

`Traceback (most recent call last):
  File "kickthemout.py", line 750, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 153, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)
`

any ideas ?

**Comment by FireC123** [comment]
i am getting the same error, have you found a solution?

**Comment by melkopisi** [comment]
nope

**Comment by k4m4** [comment]
Hi there @melkopisi. Could you please follow the issue template and supply us with significant information such as the version of python you are running, your operating system, etc. in order to investigate this issue? Thanks.

**Comment by melkopisi** [comment]
i'm using `3.6.4` as well i've `2.7.14` using `Manjaro Hakoila 17.1.18` based on ArchLinux

**Comment by Urgau** [comment]
I have the same problem on Archlinux with my configuration :

- python : 3.6.5
- pip : 9.0.1
- python-netifaces : 0.10.6
- python-nmap : 0.6.1
- python-scapy : 2.4.0
- scapy : 2.4.0

**Comment by AgeOfMarcus** [comment]
Also the same error. Here's what I get:

`RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "./kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "./kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)`

**Comment by melkopisi** [comment]
just read the new README file it works with the new instructions

**Comment by AgeOfMarcus** [comment]
@melkopisi I am still getting the same, exact, error.

**Comment by melkopisi** [comment]
Is AUR Package working now or we reinstall it manually?

**Comment by k4m4** [comment]
Re-install it manually please. I wasn't the one that created the AUR package, so please follow the manual installation.
