### ISSUE TITLE
NameError: name 'urllib' is not defined

### ISSUE THREAD

**Issue by A-thermal** [k4m4/kickthemout#286]
## Checklist for submitting an issue to `KickThemOut`:

- [x] --> I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] --> I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] -->I am running the latest version of KickThemOut.

 

- **Debian&2018.4.18**: 
- **Python3.5**: 
- **scapy3.0.0**: 
- **nmap 7.40**: 
- **sorry ,I dont understand this line **: 

<br/ >

- **Description**: 
after I knock the  lest line and enter, it do not work and give me this :

Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 129, in checkInternetConnection
    urlopen('https://google.com', timeout=3)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickthemout.py", line 740, in <module>
    if checkInternetConnection():
  File "kickthemout.py", line 131, in checkInternetConnection
    except urllib.URLError as err:
NameError: name 'urllib' is not defined

**Comment by k4m4** [comment]
Hi there @A-thermal. It turns out that this is a bug. The error you should be getting is `ERROR: It seems that you are offline. Please check your internet connection.` It seems that you do not have an internet connection. Please check your connection and try again. Thanks!

**Comment by A-thermal** [comment]
If you are in mainland of China ,perhaps,you can not use this program because of the Electronic great wall.
兄弟，如果你恰巧遇到了类似的问题，而且像我一样看到大段的报错就很蛋疼不仔细读的话，估计你会看到这条留言。我是一个新手，我觉的这个问题是墙的问题而导致无法访问报错里面的那个网址，进而导致整个程序跑不动的。  如果你有解决办法愿意告诉我的话，万分感谢。
