### ISSUE TITLE
Can't install Scapy Using TERMUX

### ISSUE THREAD

**Issue by ancientzords** [k4m4/kickthemout#304]
When i try to install requirements, this happen to me : 

```
$ pip2 install -r requirements.txt
Collecting scapy-python3 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ba/20/6f89d7f59b61e8290bafbf21556556de566f887ab8a8cabf1e998a50405f/scapy-python3-0.24.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 89kB/s
Collecting python-nmap (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/dc/f2/9e1a2953d4d824e183ac033e3d223055e40e695fa6db2cb3e94a864eaa84/python-nmap-0.6.1.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 851kB/s
Collecting netifaces (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/81/39/4e9a026265ba944ddf1fea176dbb29e0fe50c43717ba4fcf3646d099fe38/netifaces-0.10.7.tar.gz
Installing collected packages: scapy-python3, python-nmap, netifaces
  Running setup.py install for scapy-python3 ... done
  Running setup.py install for python-nmap ... done
  Running setup.py install for netifaces ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-sLohYm/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-Jrvsmg-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    checking for getifaddrs...found.
    checking for getnameinfo...found.
    checking for IPv6 socket IOCTLs...not found.
    checking for optional header files...netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...in in6 un ll atmpvc atmsvc dn irda llc.
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...yes.
    will use netlink to read routing table
    building 'netifaces' extension
    aarch64-linux-android-clang -fno-strict-aliasing -OPT:Olimit=0 -Oz -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNETIFACES_VERSION=0.10.7 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/data/data/com.termux/files/usr/include/python2.7 -c netifaces.c -o build/temp.linux-aarch64-2.7/netifaces.o
netifaces.c:1:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-sLohYm/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-Jrvsmg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-sLohYm/netifaces/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by k4m4** [comment]
Hi there. Please follow the installation guidelines as specified in the readme file. KickThemOut has been updated to work with python3 and not python2. If you come across any other problems, please do not hesitate to open a new issue. Thanks!

**Comment by saagarshaah** [comment]
Didn't worked with python 3 also

**Comment by Learn-Termux** [comment]
Not Working
```
~ $ scapy
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't open /etc/protocols file
INFO: Can't open /etc/services file
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't import matplotlib. Won't be able to plot.
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/scapy", line 8, in <module>
    sys.exit(interact())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/main.py", line 550, in interact
    SESSION, GLOBKEYS = init_session(session_name, mydict)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/main.py", line 411, in init_session
    importlib.import_module(".all", "scapy").__dict__
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/__init__.py", line 135, in <module>
    _set_conf_sockets()  # Apply config
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/config.py", line 618, in _set_conf_sockets
    conf.ifaces.reload()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/common.py", line 87, in get_if_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied

```
