### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by SyntheticJay** [k4m4/kickthemout#305]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **Kali Linux 2018.2**: 
- **Python 3.6.5**: 
- **2.4.0**: 
- **Nmap version**: 
- **https://gist.github.com/SyntheticJay/f9b23a5a9396e61b0d20f06747088763**: 

I am quite new to this whole scene, recently after finding an interest due to my friend showing me ethical hacking a while ago, I only just decided (around a month ago) to actually install kali linux and get used to how it works. and after trying to install this, I noticed this error, and I cannot seem to find anywhere which seems to resolve it, there probably is, I'm just blind.

**Comment by Nickfrid** [comment]
also having this issue.

Traceback (most recent call last):
  File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)
