### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by TheLittleRookie2** [k4m4/kickthemout#309]
root@kalilinux:~/kickthemout# python3 kickthemout.py 
Traceback (most recent call last):
  File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)

I am trying to get this work for 3 hours

**Comment by k4m4** [comment]
Hi there @TheLittleRookie2. Could you try using pull request #294? Thanks.
