### ISSUE TITLE
struct.error: argument for 's' must be a string

### ISSUE THREAD

**Issue by arnauldb** [k4m4/kickthemout#31]
Hello,

when launching kickthemout I have this message : 

```
root@arnauld:/home/arnauld/kickthemout# python kickthemout.py
 Traceback (most recent call last):
   File "kickthemout.py", line 327, in <module>
     defaultInterfaceMac = get_if_hwaddr(defaultInterface)
   File "/usr/local/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 51, in get_if_hwaddr
     addrfamily, mac = get_if_raw_hwaddr(iff)
   File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 95, in get_if_raw_hwaddr
     return struct.unpack("16xh6s8x",get_if(iff,SIOCGIFHWADDR))
   File "/usr/local/lib/python2.7/dist-packages/scapy/arch/common.py", line 19, in get_if
     ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff))
 struct.error: argument for 's' must be a string
```

thanks for any help,

**Comment by k4m4** [comment]
Should work now. Check it out and let me know please.
Thanks!

**Comment by arnauldb** [comment]
thanks for that quick help, it works perfectly now.
![selection_010](https://cloud.githubusercontent.com/assets/13196747/22175092/713242f4-dfee-11e6-84a0-cbc417fd1a98.png)

**Comment by k4m4** [comment]
No problem. Thank you for submitting! :)
