### ISSUE TITLE
Websploit Error!!!!!

### ISSUE THREAD

**Issue by fsocietyazec** [k4m4/kickthemout#330]
websploit
Traceback (most recent call last):
File "/usr/bin/websploit", line 57, in <module>
from modules import arp_poisoner
File "/usr/share/websploit/modules/arp_poisoner.py", line 11, in <module>
from scapy.all import *
File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
from .config import *
File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
from .data import *
File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by robbix1206** [comment]
You seem to be running it under Python 2.X and not Python 3.X

**Comment by fsocietyazec** [comment]
Thank you

**Comment by profionaldhim** [comment]
Pelase not working with me
Us error

**Comment by profionaldhim** [comment]
how to fix error ¿¿
