### ISSUE TITLE
issue on running kickthemout 

### ISSUE THREAD

**Issue by elswerky** [k4m4/kickthemout#331]
i get this error on running kickthemout on arch either by installing it from the aur or by using the files downlaoded from here from github 

it was working before a few days ago 
this is the error i get 

Traceback (most recent call last):
  File "/usr/share/kickthemout/kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "/usr/share/kickthemout/kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)

**Comment by robbix1206** [comment]
Are you sure that you are running it with Python 3 with all modules installed for python 3 ?

**Comment by k4m4** [comment]
Hi there @elswerky. You can use the `-p` option to send more arp packets to the victim. For more info, run `python3 kickthemout.py -h`.

**Comment by k4m4** [comment]
Closing due to inactivity.
