### ISSUE TITLE
Kamene problems in Arch

### ISSUE THREAD

**Issue by quiddi-github** [k4m4/kickthemout#371]
- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

- **OS name & version**: 
- **Python version**: 
- **Kamene version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/quiddi-github/db1bc0d01330614da6940a6268f1620c)**: 

<br/ >

- **Description**: 

Hi guys,
I have problems since the last Arch update with pacman (pacman -Syu) to rum kickthemout well. when I do
`sudo python3 kickthemout.py`
I get:
`ERROR: --- Error in child 3607
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/kamene/sendrecv.py", line 89, in sndrcv
    pks.send(p)
  File "/usr/lib/python3.7/site-packages/kamene/arch/linux.py", line 408, in send
    self.outs.sendto(sx, sdto)
OSError: [Errno 22] Invalid argument
`
Thanks for your help in advance

**Comment by k4m4** [comment]
Interesting, this is probably a bug in kamene. I will try to reproduce.

**Comment by k4m4** [comment]
- [This issue](https://github.com/secdev/scapy/issues/1683) seems to be addressing a similar problem.

**Comment by quiddi-github** [comment]
Thanks for your reply. Changing the Maximum Transfer Unit does not solve this problem. My network card is already working with 1500. I also tried some other mtu values, fromm 100 to 1500 in hundreds of steps.
