### ISSUE TITLE
Trackback most recantcall ( using termux to run linux)

### ISSUE THREAD

**Issue by Scholes13** [k4m4/kickthemout#413]
I used android and use termux to run linux kalinethunter so i got this 

`root@localhost:~/kickthemout# python3 kickthemout.py
Traceback (most recent call last):
  File "kickthemout.py", line 753, in <module>      defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence` i already reinstall kickthemout but still got nothing

**Comment by k4m4** [comment]
Hi there @Scholes13. Unfortunately, KickThemOut does not support Android devices. Thanks!
