### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by aashishvinu** [k4m4/kickthemout#461]
```
Traceback (most recent call last):
  File "kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence
```

**Comment by lukalafaye** [comment]
Same here, on ubuntu 16 04

**Comment by franklinworm** [comment]
Same here

**Comment by Adrish-S** [comment]
Same here
