### ISSUE TITLE
Traceback error on android

### ISSUE THREAD

**Issue by franklinworm** [k4m4/kickthemout#467]
Traceback (most recent call last):
  File "kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence

**Comment by forest-cat** [comment]
I am getting the same error maybe someone know how to help, i am using with python3, when i try to install netifaces with pip2 then it fails compiling the module.

**Comment by KhaidirArt** [comment]
Does not support on android
Use another tools
Example netcut.
