### ISSUE TITLE
Kickthemout won't start, Python Error

### ISSUE THREAD

**Issue by MakrelenBoss** [k4m4/kickthemout#492]
Hello,
I am on Kali Linux and just tried to run kickthemout. I installed the requirements.txt with only one error, but I don't think that it is critical. But always when I try to run the python file, it gives me this error message:

`
Traceback (most recent call last):
  File "C:\Users\Mika\kickthemout\kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "C:\Users\Mika\kickthemout\kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence`

How to fix it? And what is the Problem? Please help me fast. Thank You.

**Comment by AstroOrbis** [comment]
`C:` means a windows drive, this software isn't compatible with Windows I believe.

**Comment by MakrelenBoss** [comment]
On Linux Mint and Kali Linux (with and without sudo) happened the same.

AstroOrbis <notifications@github.com> schrieb am Sa., 6. März 2021, 05:07:
