### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by liltato69** [k4m4/kickthemout#493]
sudo python3 kickthemout.py
CRITICAL: Can't open /proc/net/dev !
CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
Traceback (most recent call last):
  File "/root/kickthemout/kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "/root/kickthemout/kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence

**Comment by Mus90YT** [comment]
1 year ago and no response...
