### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Mus90YT** [k4m4/kickthemout#506]
Hi, when I try to install it (after checking requirements) I got this error:

root@localhost:~/kickthemout# python3 kickthemout.py
CRITICAL: Can't open /proc/net/dev !
CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
Traceback (most recent call last):
  File "/root/kickthemout/kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "/root/kickthemout/kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence

I've tried so much things but no one didn't work. Please help me, THANKS!

**Comment by Michaelbai2631** [comment]
Are you install kali linux in termux?.the problem is the same as mine
