### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Mus90YT** [k4m4/kickthemout#507]
## Checklist for submitting an issue to `KickThemOut`:

- [X ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [X ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [X ] I am running the latest version of KickThemOut.

 

- **OS name & version**:  Kali Linux 2022.1
- **Python version**:  3.9.12
- **Scapy version**:  2.4.4
- **Nmap version**:  7.92
- **Link of [Gist](https://gist.github.com/)**: 
Can't create anyone. 
<br/ >

- **Description**:  I can't open it

 HI, after I've typed "./configure", "make", "make install" and "python kickthemout.py" I got this error 

CRITICAL: Can't open /proc/net/dev !
CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
Traceback (most recent call last):
File "/root/kickthemout/kickthemout.py", line 756, in
defaultInterface = getDefaultInterface()
File "/root/kickthemout/kickthemout.py", line 154, in getDefaultInterface
network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence

I've tried u installing the requirements and installing them again, but it didn't work.

**Comment by Michaelbai2631** [comment]
the problem is the same as mine
