### ISSUE TITLE
ValueError: max() arg is an empty sequence怎么解决

### ISSUE THREAD

**Issue by cdd300** [k4m4/kickthemout#510]
Traceback (most recent call last):
  File "D:\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "D:\MockingBird-main\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by Yuyang-Wu** [comment]
Looks like you are in a windows OS.
In README it says "Not compatible with Windows."
